config/routes.rb
# frozen_string_literal: true

require 'saasy/constraints/subdomain_required'

Saasy::Engine.routes.draw do
  # Check for subdomains before matching any other routes
  constraints(Saasy::Constraints::SubdomainRequired) do
    scope module: 'accounts' do
      root to: 'dashboard#index', as: :account_root
      resources :users, only: %i[index destroy]
      resources :invitations, only: %i[new create] do
        member do
          get :accept
          patch :accepted
        end
      end
    end
  end

  devise_for :users, class_name: 'Saasy::User', module: :devise

  root to: 'home#index'
  get 'signup' => 'signups#new',     as: :new_signup
  post 'signup' => 'signups#create', as: :signups

  namespace :admin do
    root to: 'dashboard#index'
    resources :users, except: %i[edit update]
    resources :accounts
  end
end

app/models/saasy/account.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: saasy_accounts
#
#  id           :integer          not null, primary key
#  company_name :string(50)       not null
#  subdomain    :string(50)       not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  deleted_at   :datetime
#

module Saasy
  class Account < ApplicationRecord
    acts_as_paranoid

    before_validation :normalise_data

    has_many :memberships
    has_many :users, through: :memberships
    has_many :invitations
    has_many :things, class_name: Saasy.thing_class

    validates :company_name, presence: true, length: { minimum: 2, maximum: 50 }
    validates :subdomain, presence: true, length: { minimum: 2, maximum: 50 }
    validates :subdomain, uniqueness: true
    validates_format_of :subdomain, with: /\A[a-zA-Z]+\z/, message: 'only letters are valid subdomains'
    validates :subdomain, exclusion: {
      in: %w[www admin about beta billing blog cdn chat cpanel download email
             search smtp pop mail mobile my news payment porn purchase affiliate],
      message: '%<value>% is not a valid subdomain.'
    }

    # Allow user roles to be set at the account level using the Rolify gem
    resourcify

    private

    def normalise_data
      # http://www.rubydoc.info/gems/rubocop/0.43.0/RuboCop/Cop/Style/SafeNavigation
      subdomain&.downcase! # same as subdomain.downcase! if !subdomain.nil?
      subdomain&.delete!(' ') # don't allow any spaces in subdomains
    end
  end
end

app/controllers/saasy/accounts/dashboard_controller.rb
# frozen_string_literal: true

require_dependency 'saasy/application_controller'

module Saasy
  module Accounts
    class DashboardController < ApplicationController
      include Saasy::AccountConcerns
      def index; end
    end
  end
end

app/controllers/saasy/accounts/invitations_controller.rb
# frozen_string_literal: true

require_dependency 'saasy/application_controller'

module Saasy
  module Accounts
    class InvitationsController < ApplicationController
      include AccountConcerns
      skip_before_action :authorize_user!, only: %i[accept accepted]
      after_action :verify_authorized, except: %i[accept accepted]

      def new
        @invitation = current_account.invitations.new
        authorize! @invitation
      end

      def create
        @invitation = current_account.invitations.new(invitation_params)
        authorize! @invitation
        invite_user
      end

      def accept
        store_location_for(:user, request.fullpath)
        @invitation = Invitation.find_by!(token: params[:id])
      end

      def accepted
        @invitation = Invitation.find_by!(token: params[:id])
        signup_new_user unless user_signed_in?
        add_user_to_account
        redirect_to root_url(subdomain: current_account.subdomain)
      end

      private

      def authorize!(invitation)
        return if authorize invitation
        flash[:alert] = I18n.t('authorization.failure')
        redirect_to root_url(subdomain: current_account.subdomain)
      end

      def invitation_params
        params.require(:invitation).permit(:email)
      end

      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end

      def signup_new_user
        result = Saasy::Users::CreateUser.call(user_params)
        if result.success?
          sign_in(result.user)
        else
          flash[:alert] = I18n.t('account.create.failure')
          render :accept
        end
      end

      def add_user_to_account
        result = Saasy::Memberships::AddUserToAccount.call(
          user: current_user,
          account: current_account
        )
        if result.success?
          flash[:notice] = I18n.t('invitation.accept.success', company_name: current_account.company_name)
        else
          flash[:alert] = I18n.t('invitation.accept.failure', company_name: current_account.company_name)
        end
      end

      def invite_user
        result = Saasy::Invitations::InviteUserToAccount.call(
          params: invitation_params,
          account: current_account
        )
        if result.success?
          flash[:notice] = I18n.t(result.message, email: result.invitation.email)
          redirect_to root_url
        else
          flash.now[:alert] = I18n.t(result.message, email: result.invitation.email)
          render :new
        end
      end
    end
  end
end

app/controllers/saasy/accounts/users_controller.rb
# frozen_string_literal: true

require_dependency 'saasy/application_controller'

module Saasy
  module Accounts
    class UsersController < ApplicationController
      include Saasy::AccountConcerns

      def index; end

      def destroy
        result = Saasy::Memberships::RemoveUserFromAccount.call(user: user_params, account: current_account)
        process_deletion_result(result)
        redirect_to users_path
      end

      private

      def user_params
        User.find(params[:id])
      end

      def process_deletion_result(result)
        if result.success?
          flash[:notice] = I18n.t(result.message, user: result.membership.user.email)
        else
          flash[:alert] = I18n.t(result.message, user: result.membership.user.email)
        end
      end
    end
  end
end

app/controllers/saasy/admin/accounts_controller.rb
# frozen_string_literal: true

require_dependency 'saasy/application_controller'

module Saasy
  module Admin
    class AccountsController < ApplicationController
      include Saasy::AdminConcerns

      before_action :find_account, only: %i[edit update show destroy]

      def index
        @accounts = Saasy::Account.all
      end

      def new
        @account = Saasy::Account.new
      end

      def create
        @account = Saasy::Account.new
        result = Saasy::Accounts::CreateAccount.call(account_params)
        if result.success?
          flash[:notice] = I18n.t(result.message)
          redirect_to admin_account_path(result.account)
        else
          flash.now[:alert] = I18n.t(result.message)
          render :new
        end
      end

      def show; end

      def edit; end

      def update
        result = Saasy::Accounts::UpdateAccount.call(
          account: @account,
          new_attributes: account_params
        )
        if result.success?
          flash[:notice] = I18n.t(result.message)
          redirect_to admin_account_path(result.account)
        else
          flash.now[:alert] = I18n.t(result.message)
          render :edit
        end
      end

      def destroy
        result = Saasy::Accounts::DeleteAccount.call(account: @account)
        if result.success?
          flash[:notice] = I18n.t(result.message)
          redirect_to admin_accounts_path
        else
          flash[:alert] = I18n.t(result.message)
          redirect_to(request.referrer || admin_account_path(@account))
        end
      end

      private

      def find_account
        @account = Saasy::Account.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = I18n.t('admin.errors.account_not_found')
        redirect_to(request.referrer || admin_account_path)
      end

      def account_params
        params.require(:account).permit(:company_name, :subdomain)
      end
    end
  end
end

app/helpers/saasy/accounts/dashboard_helper.rb
# frozen_string_literal: true

module Saasy
  module Accounts
    module DashboardHelper
    end
  end
end

app/helpers/saasy/admin/accounts_helper.rb
# frozen_string_literal: true

module Saasy
  module Admin::AccountsHelper
  end
end

app/views/saasy/admin/accounts/_account_members.html.erb
<% if @account.users.count.zero? %>
  This account currently does not have any users.
<% else %>
  This account has the following users:
  <table class="account-members">
    <thead>
      <tr>
        <td>Email:</td>
        <td>Account Role</td>
        <td>Joined:</td>
        <td>Sign in Count:</td>
        <td>Last Signed in</td>
        <td>Last Signed in IP</td>
        <td>Actions</td>
      </tr>
    </thead>
    <tbody>
      <% @account.users.each do |user| %>
        <tr data-user-id="<%= user.id %>">
          <td><%= user.email %></td>
          <td><%= "Admin" if user.has_role? :admin, @account %></td>
          <td><%= user.created_at %></td>
          <td><%= user.sign_in_count %></td>
          <td><%= user.last_sign_in_at %></td>
          <td><%= user.last_sign_in_ip %></td>
          <td>
            <%= link_to "User Details", admin_user_path(user) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/saasy/admin/accounts/edit.html.erb
<h1>Edit <%= @account.company_name %> Account</h1>

<%= form_for(@account, url: admin_account_path) do |f| %>
  <% if @account.errors.any? %>
  <ul>
    <% @account.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <p>
    <%= f.label :company_name %>
    <%= f.text_field :company_name, autofocus: true %>
  </p>
  <p>
    <%= f.label :subdomain %>
    <%= f.text_field :subdomain %>
  </p>

  <%= f.submit "Update Account" %>
<% end %>

app/views/saasy/admin/accounts/index.html.erb
<h1>Accounts</h1>

<%= link_to "Create Account", new_admin_account_path %>

<table>
  <thead>
    <tr>
      <td>Company Name:</td>
      <td>Joined:</td>
      <td>Subdomain:</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.company_name %></td>  
        <td><%= account.created_at %></td>
        <td><%= account.subdomain %></td>
        <td>
          <%= link_to "View Details", admin_account_path(account) %>
          <%= link_to "Edit", edit_admin_account_path(account) %>
          <%= link_to "Delete", admin_account_path(account), method: :delete, data: { confirm: 'Are you sure?' }  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/saasy/admin/accounts/new.html.erb
<%= form_for(@account, url: admin_accounts_path) do |f| %>
  <% if @account.errors.any? %>
  <ul>
    <% @account.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <p>
    <%= f.label :company_name %>
    <%= f.text_field :company_name, autofocus: true %>
  </p>
  <p>
    <%= f.label :subdomain %>
    <%= f.text_field :subdomain %>
  </p>

  <%= f.submit "Create Account" %>
<% end %>

app/views/saasy/admin/accounts/show.html.erb
<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <td>Company Name:</td>
      <td>Joined:</td>
      <td>Subdomain:</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @account.company_name %></td>  
      <td><%= @account.created_at %></td>
      <td><%= @account.subdomain %></td>
      <td>
        <%= link_to "Delete", admin_account_path(@account), method: :delete, data: { confirm: 'Are you sure?' }  %>
      </td>
    </tr>
  </tbody>
</table>

<%= render 'account_members' %>